### ISSUE TITLE
[Request] Accept an FnMut cost function 

### ISSUE THREAD

**Issue by lovasoa** [mich101mich/hierarchical_pathfinding#1]
**Is your feature request related to a problem? Please describe.**
I am currently using a dijkstra implementation from pathfinding crate for my [rust seam carving library](https://github.com/lovasoa/seamcarving). I was considering switching to hierarchical_pathfinding, but my cost function uses caching, so it needs to be an `FnMut`. `PathCache::new` does not accept that.

**Describe the solution you'd like**
Replacing `impl Fn(Point) -> isize` with `impl FnMut(Point) -> isize` in the PathCache methods.

**Comment by mich101mich** [comment]
Changed in the [0.3.0 Release](https://github.com/mich101mich/hierarchical_pathfinding/releases/tag/0.3.0).

If this breaks any Applications (it shouldn't but who knows) or future Features then I might have to change it back.

**Comment by lovasoa** [comment]
Thank you !
