### ISSUE TITLE
[Bug] 0.4 Panics with Added disconnected Path

### ISSUE THREAD

**Issue by Elabajaba** [mich101mich/hierarchical_pathfinding#3]
**Describe the bug**
0.4.1 and 0.4.2 panic with Added disconnected Path when trying to find longer paths.

**To Reproduce**
Example: https://github.com/Elabajaba/hierarchical_pathfinding_example/blob/main/src/main.rs

**Expected behavior**
It doesn't panic.

**Actual behavior**
thread 'main' panicked at 'Added disconnected Path: expected (56, 3), got (56, 0)'

**Additional info**
ManhattanNeighborhood with panic on a 16x16 grid with start(0,0) and end(15,15). MooreNeighborhood is fine with that grid, but panics on a larger grid (tested 64x64 with start (0,0) and tested both end (63,0) and end (63, 63), both panic)

I'm unable to reproduce this error with 0.3

**Comment by mich101mich** [comment]
Indeed, seems like there was an Index bug in one of the 0.4 changes that never came up in testing, sorry.

Can you check if the newest commit fixes everything on your end before I publish to crates.io? Your example repo now works with the current master. You might have to somehow force cargo to pull the repo again.

**Comment by Elabajaba** [comment]
The new commit fixes it on my example repo and my other program where I discovered the bug.

Thanks for the speedy fix.

**Comment by mich101mich** [comment]
Published as Version [`0.4.3`](https://github.com/mich101mich/hierarchical_pathfinding/releases/tag/0.4.3). That version also includes another speedup (that hopefully _doesn't_ break things this time), so you should probably update to that version.
