### ISSUE TITLE
[Bug] Added disconnected Path error with find_closest_goal

### ISSUE THREAD

**Issue by rparrett** [mich101mich/hierarchical_pathfinding#7]
**Describe the bug**

For context, I am trying to pathfind an entity on a manhattan grid to "any neighboring tile of the goal." This strategy generally seems to work, but I am seeing occasional strange behavior (paths going through impassable tiles, suboptimal paths, paths sometimes not including the first step, and a separate panic that I haven't been able to reproduce minimally.)

But I noticed that when I choose a goal two spaces away, and then choose a goal of the previous starting point, I get a panic. I also occasionally see this panic when choosing a goal one space away.

This doesn't seem to be an issue when using `find_path`, but **does** seem to be an issue when using `find_paths` as well.

This happens with/without the `parallel` feature enabled.

**To Reproduce**

```rust
use hierarchical_pathfinding::prelude::*;

type Grid = [[usize; 7]; 7];

const COST_MAP: [isize; 3] = [1, 10, -1]; // now const for ownership reasons

// only borrows the Grid when called
fn cost_fn(grid: &Grid) -> impl '_ + Sync + Fn((usize, usize)) -> isize {
    move |(x, y)| COST_MAP[grid[y][x]]
}

fn neighbors(x: usize, y: usize) -> [(usize, usize); 4] {
    [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
}

fn main() {
    // 0 = empty, 1 = swamp, 2 = wall
    let grid: Grid = [
        [2, 2, 0, 0, 0, 0, 0],
        [2, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 2, 2, 0, 0],
        [0, 1, 0, 1, 2, 0, 0],
        [0, 0, 0, 2, 2, 0, 0],
        [0, 0, 0, 0, 0, 0, 2],
        [0, 0, 0, 0, 0, 2, 2],
    ];
    let (width, height) = (grid.len(), grid[0].len());

    let pathfinding = PathCache::new(
        (width, height),
        cost_fn(&grid),
        ManhattanNeighborhood::new(width, height),
        PathCacheConfig::with_chunk_size(3),
    );

    let path = pathfinding.find_closest_goal((1, 1), &neighbors(1, 3), cost_fn(&grid));
    assert!(path.is_some());
    let path = pathfinding.find_closest_goal((1, 3), &neighbors(1, 1), cost_fn(&grid));
    assert!(path.is_some());
}
```

**Expected behavior**

No panic

**Actual behavior**

```
thread 'main' panicked at /Users/robparrett/src/hierarchical_pathfinding/src/path/abstract_path.rs:150:9:
Added disconnected Path: expected (2, 2), got (2, 1)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: hierarchical_pathfinding::path::abstract_path::AbstractPath<N>::add_path
             at ./src/path/abstract_path.rs:150:9
   3: hierarchical_pathfinding::path_cache::PathCache<N>::resolve_paths
             at ./src/path_cache.rs:1357:17
   4: hierarchical_pathfinding::path_cache::PathCache<N>::find_paths_internal
             at ./src/path_cache.rs:830:9
   5: hierarchical_pathfinding::path_cache::PathCache<N>::find_closest_goal
             at ./src/path_cache.rs:740:9
   6: test::main
             at ./examples/test.rs:36:16
   7: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Elabajaba** [comment]
~~It's been awhile since I've used this library, but iirc you need to filter walls yourself in the `neighbours` function.~~

edit: Looking at an old project now I'm pretty sure I'm wrong.

**Comment by rparrett** [comment]
I would love if that were spelled out in the docs if that's the case.

I tested it out, and it does seem to help with the panicking. So even if it's not intended behavior, it's a nice workaround for now.

**Comment by rparrett** [comment]
Maybe I spoke too soon. Still seeing panics (the same one, but also a new one) when manually filtering the goals.

```
thread 'main' panicked at /Users/robparrett/src/hierarchical_pathfinding/src/path_cache.rs:1320:50:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:180:5
   3: <hierarchical_pathfinding::path::generic_path::Path<P> as core::ops::index::Index<usize>>::index
             at ./src/path/generic_path.rs:72:10
   4: hierarchical_pathfinding::path_cache::PathCache<N>::resolve_paths
             at ./src/path_cache.rs:1320:50
   5: hierarchical_pathfinding::path_cache::PathCache<N>::find_paths_internal
             at ./src/path_cache.rs:830:9
   6: hierarchical_pathfinding::path_cache::PathCache<N>::find_closest_goal
             at ./src/path_cache.rs:740:9
   7: test::pathfind
             at ./examples/test.rs:82:9
   8: test::main
             at ./examples/test.rs:41:16
   9: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

New example:

```rust
use hierarchical_pathfinding::prelude::*;

type Grid = [[usize; 7]; 7];

const COST_MAP: [isize; 3] = [1, 10, -1]; // now const for ownership reasons

// only borrows the Grid when called
fn cost_fn(grid: &Grid) -> impl '_ + Sync + Fn((usize, usize)) -> isize {
    move |(x, y)| COST_MAP[grid[y][x]]
}

fn neighbors(pos: (usize, usize)) -> [(isize, isize); 4] {
    [
        (pos.0 as isize + 1, pos.1 as isize),
        (pos.0 as isize - 1, pos.1 as isize),
        (pos.0 as isize, pos.1 as isize + 1),
        (pos.0 as isize, pos.1 as isize - 1),
    ]
}

fn main() {
    // 0 = empty, 1 = swamp, 2 = wall
    let grid: Grid = [
        [2, 2, 0, 0, 0, 0, 0],
        [2, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 2, 2, 0, 0],
        [0, 1, 0, 1, 2, 0, 0],
        [0, 0, 0, 2, 2, 0, 0],
        [0, 0, 0, 0, 0, 0, 2],
        [0, 0, 0, 0, 0, 2, 2],
    ];
    let (width, height) = (grid.len(), grid[0].len());

    let pathfinding = PathCache::new(
        (width, height),
        cost_fn(&grid),
        ManhattanNeighborhood::new(width, height),
        PathCacheConfig::with_chunk_size(3),
    );

    let path = pathfind((1, 1), (3, 1), &grid, &pathfinding);
    assert!(path.is_some());
    assert!(path.unwrap().len() > 1);
    let path = pathfind((3, 1), (5, 1), &grid, &pathfinding);
    assert!(path.is_some());
    assert!(path.unwrap().len() > 1);
    let path = pathfind((5, 1), (3, 1), &grid, &pathfinding);
    assert!(path.is_some());
    assert!(path.unwrap().len() > 1);
    let path = pathfind((3, 1), (1, 1), &grid, &pathfinding);
    assert!(path.is_some());
    assert!(path.unwrap().len() > 1);
}

fn pathfind(
    pos: (usize, usize),
    goal: (usize, usize),
    grid: &Grid,
    pathfinding: &PathCache<ManhattanNeighborhood>,
) -> Option<Vec<(usize, usize)>> {
    let valid_neighbors = neighbors(goal)
        .iter()
        .cloned()
        .filter(|n| n.0 >= 0 && n.1 >= 0 && cost_fn(&grid)((n.0 as usize, n.1 as usize)) != -1)
        .map(|n| (n.0 as usize, n.1 as usize))
        .collect::<Vec<_>>();
    println!("valid_neighbors: {:?}", valid_neighbors);
    let (_goal, path) =
        pathfinding.find_closest_goal(pos, &valid_neighbors.as_slice(), cost_fn(&grid))?;
    Some(path.resolve(cost_fn(&grid)))
}
```

**Comment by mich101mich** [comment]
I did some debugging and this seems like at least one bug from several optimizations conflicting with each other. 😞

Explanation of the initial panic:
The first chunk of the grid (you set chunk_size to 3) looks like this:
```
+---+---+---++---
|###|###|   ||   
+---+---+---++---
|###| s | 0 ||   
+---+---+---++---
|~~~| g | 1 ||###
+===+===+===++===
|   |~~~|   ||   
```
Where `s` is the start, `g` is the goal that ends up with the shortest path, and `0` and `1` are nodes. The way that hierarchical_pathfinding works is that it finds the closest node to each start/end (`0` for `s`, `1` for `g` in this case), and then finds a path along the node graph rather than the grid. So in this case, the final path would be `s -> 0 -> 1 -> g`. While that looks horribly inefficient to us, that is the tradeoff of this approach, which is aimed at much longer paths.

This is the reason why there is a configurable fallback for really short paths (which, side note, isn't even used in this case; I'll need to fix that as well), and the root cause of the panic: An optimization to shorten the start and end of a path if two sections are in the same chunk. So in this case it tries to calculate a path from `s` to `1` directly, and from `0` to `g` directly, which then causes the panic because it wants to connect the paths `s -> ... -> 1` to `0 -> ... -> g`, which doesn't work.

I haven't checked your second example yet, because I want to fix this one first, which with my current amount of free time will take some days, sorry.

**Comment by rparrett** [comment]
Fascinating. I appreciate you taking a look. I'm in a bit of a crunch for time on this project, so I swapped in the `pathfinding` crate instead for now. But I may be able to help investigate in the future.

Could you comment on whether it **should** be necessary to manually filter goals that aren't walkable?

> The first chunk of the grid (you set chunk_size to 3) looks like this:

Thanks for pointing this out. I was also using the same size in my project, having never looked at what an appropriate chunk size would be. It looks like your docs are providing all the information I need to make a determination about that, and 3 is definitely not ideal outside of the small example grids.

**Comment by mich101mich** [comment]
As for the non-walkable goals: I specifically designed this crate to allow finding paths to a solid wall, because 90% of my use case back then revolved around that.

**Comment by mich101mich** [comment]
I have (from what I can tell) fixed this bug. The examples that you provided are working now (see [here](https://github.com/mich101mich/hierarchical_pathfinding/pull/8/files#diff-86295c1c1f7db59e37fed4597532f86baa09aa279d68a8e4c2797d07ebfcf1a7R154-R194) and [here](https://github.com/mich101mich/hierarchical_pathfinding/pull/8/files#diff-86295c1c1f7db59e37fed4597532f86baa09aa279d68a8e4c2797d07ebfcf1a7R201-R275)), although for the second example I had to change the assertions: The shortest path from `(1,1)` to a neighbor of `(3,1)` has `len() == 1`, as `(2,1)` is a neighbor and immediately reachable.

@rparrett  Did you encounter any other panics aside from the examples that you posted?

**Comment by rparrett** [comment]
I think those were the only two panics I experienced. I was scrambling at the time and ended up switching to the `pathfinding` crate and just doing astar. This crate seems ideal for the project though so I'll circle back and try it out again eventually.
